# Gradle で Cucumberのテストを実行します
name: Run Cucumber Test

on:
  # mainブランチへPull Requestを行うブランチ と Marge後のmainブランチを対象にします
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  # このWorkflowをGitHub Actionsから手動で実行することも許可
  workflow_dispatch:

jobs:
  build:

    # 実行環境はUbuntu
    runs-on: ubuntu-latest

    steps:
      # リポジトリをcheckoutする
      - uses: actions/checkout@v3

      # OpenJDK のセットアップ
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # gradle-wrapper.jar の整合性確認
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Gradleアクションを利用する
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # ビルトの実行 (Cucumber reportsにCI情報を出力する）
      - name: Build with Gradle
        run: ./gradlew clean check
        env:
          CI: true
